-- Run this in the Supabase SQL editor.

create extension if not exists "pgcrypto";

create table if not exists public.shared_files (
  id bigint generated by default as identity primary key,
  file_id uuid not null unique,
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  file_size bigint not null,
  hashed_password text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  download_count integer not null default 0,
  max_downloads integer
);

create index if not exists idx_shared_files_file_id on public.shared_files(file_id);
create index if not exists idx_shared_files_expires_at on public.shared_files(expires_at);

alter table public.shared_files enable row level security;

-- Deny direct anon access. Server uses service role key.
drop policy if exists "deny_anon_select" on public.shared_files;
create policy "deny_anon_select"
on public.shared_files
for select
to anon
using (false);

drop policy if exists "deny_anon_insert" on public.shared_files;
create policy "deny_anon_insert"
on public.shared_files
for insert
to anon
with check (false);

-- Storage bucket notes:
-- 1) Create a bucket named secure-files (or your env value).
-- 2) Set bucket to PRIVATE.
-- 3) Service role key bypasses RLS and can upload/create signed URLs.
